[package]
name = "pbrpbr"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.25.0"
glam = {version = "0.32.0", features = ["bytemuck"]}
gltf = {version = "1.4.1", features = ["KHR_lights_punctual"]}
image = "0.25.9"
pollster = "0.4.0"
wgpu = "28.0.0"
winit = "0.30.12"
